services:
  comfyui:
    image: yanwk/comfyui-boot:latest
    container_name: comfyui
    restart: unless-stopped

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CLI_ARGS=--listen 0.0.0.0

    ports:
      - "8188:8188"

    volumes:
      - comfyui_data:/root
      - comfyui_models:/root/ComfyUI/models
      - comfyui_output:/root/ComfyUI/output
      - comfyui_input:/root/ComfyUI/input
      - comfyui_custom_nodes:/root/ComfyUI/custom_nodes

    networks:
      - comfyui_net

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  comfyui_data:
  comfyui_models:
  comfyui_output:
  comfyui_input:
  comfyui_custom_nodes:

networks:
  comfyui_net:
    name: comfyui_net
    driver: bridge
